### PR TITLE
✨ Add support for multi-controlled gates to ZX package

### LINKED ISSUE #1357: ✨ Add multi-controlled gate support to ZX package
### Problem Statement

The existing transformations from `qc::QuantumComputation` to `zx::Diagram` are limited to one- and two-qubit gates (with the exception of `ccx`). See https://github.com/munich-quantum-toolkit/core/blob/main/include/mqt-core/zx/FunctionalityConstruction.hpp

### Proposed Solution

The respective functionality should be extended so that multi-controlled gates (particularly, multi-controlled X and Z gates).

### PR DESCRIPTION
**Pull request by keefehuang**
## Description

Add CRZ, MCX, MCZ, MCRZ functionality to ZX package.
Add convenience addCCZ function as it avoids one additional Hardamard edge (optimizes it away).

Fixes #1357

## Checklist:

- [X] The pull request only contains commits that are focused and relevant to this change.
- [X] I have added appropriate tests that cover the new/changed functionality.
- [X] ~~I have updated the documentation to reflect these changes.~~
- [x] I have added entries to the changelog for any noteworthy additions, changes, fixes, or removals.
- [x] ~~I have added migration instructions to the upgrade guide (if needed).~~
- [x] The changes follow the project's style guidelines and introduce no new warnings.
- [x] The changes are fully tested and pass the CI checks.
- [X] I have reviewed my own code changes.

### CODE REVIEW

File: src/zx/FunctionalityConstruction.cpp [hunk 1]
```diff
@@ -307,6 +307,127 @@ void FunctionalityConstruction::addCcx(ZXDiagram& diag, const Qubit ctrl0,
...
+                                        std::vector<Vertex>& qubits) {
+
+  const Qubit nextControl = controls.back();
+  controls.pop_back();
+
+  addCrz(diag, phase / 2, nextControl, target, qubits);
+  addMcx(diag, controls, target, qubits);
+  addCrz(diag, -phase / 2, nextControl, target, qubits);
+  addMcx(diag, controls, target, qubits);
+}
```
[the remark this answers is not in the document]
Comment (keefehuang) [reply src/zx/FunctionalityConstruction.cpp:429]: This is unreachable code due to the checks prior and lowers the code coverage to unacceptable levels if added.

File: test/zx/test_zx_functionality.cpp [hunk 2]
```diff
@@ -219,14 +219,329 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+
+  fullReduce(d);
+
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+  EXPECT_TRUE(d.connected(d.getInput(2), d.getOutput(2)));
+  EXPECT_TRUE(d.connected(d.getInput(3), d.getOutput(3)));
+}
```
[the remark this answers is not in the document]
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp]: This decomposition uses an additional unused qubit. Thus, qubit 3 should be checked.

File: test/zx/test_zx_functionality.cpp [hunk 3]
```diff
@@ -219,14 +219,318 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+  auto dPrime = FunctionalityConstruction::buildFunctionality(&qcPrime);
+
+  d.concat(dPrime.invert());
+
+  fullReduce(d);
+
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+}
```
[the remark this answers is not in the document]
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp]: Added

File: test/zx/test_zx_functionality.cpp [hunk 4]
```diff
@@ -219,14 +219,337 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+  d.concat(dPrime.invert());
+
+  fullReduce(d);
+
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+  EXPECT_TRUE(d.connected(d.getInput(2), d.getOutput(2)));
+}
```
[the remark this answers is not in the document]
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp]: The check is performed elsewhere. These gates are tested to be transformable in another test.

File: test/zx/test_zx_functionality.cpp [hunk 5]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+  auto dPrime = FunctionalityConstruction::buildFunctionality(&qcPrime);
+
+  d.concat(dPrime.invert());
+
+  fullReduce(d);
+
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
 }
```
[the remark this answers is not in the document]
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp:346]: The tests can be made more concrete overall. Will implement this in the overhaul of the tests when it happens.

File: test/zx/test_zx_functionality.cpp [hunk 6]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+
+  fullReduce(d);
+
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+  EXPECT_TRUE(d.connected(d.getInput(2), d.getOutput(2)));
+  EXPECT_TRUE(d.connected(d.getInput(3), d.getOutput(3)));
+}
```
[the remark this answers is not in the document]
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp]: This decomposition uses additional qubits. Thus, the last is required.

File: test/zx/test_zx_functionality.cpp [hunk 7]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+  d.concat(dPrime.invert());
+
+  fullReduce(d);
+
+  EXPECT_TRUE(FunctionalityConstruction::transformableToZX(&qc));
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+}
```
[the remark this answers is not in the document]
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp:219]: The gates that are test are already checked elsewhere. These are redundant tests.

File: test/zx/test_zx_functionality.cpp [hunk 8]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+
+  fullReduce(d);
+
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+  EXPECT_TRUE(d.connected(d.getInput(2), d.getOutput(2)));
+  EXPECT_TRUE(d.connected(d.getInput(3), d.getOutput(3)));
+}
```
[the remark this answers is not in the document]
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp]: Will have to update the ZX simplification algorithms. These will do for now.

File: test/zx/test_zx_functionality.cpp [hunk 9]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
```
[the remark this answers is not in the document]
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp]: Will have to update the ZX simplification algorithms. These will do for now.

File: test/zx/test_zx_functionality.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp]: Yes, please

File: test/zx/test_zx_functionality.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp]: Addressed in comment above

File: test/zx/test_zx_functionality.cpp [hunk 10]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+  EXPECT_TRUE(d.connected(d.getInput(2), d.getOutput(2)));
+}
+TEST_F(ZXFunctionalityTest, CCZ) {
+  const std::string testfile = "OPENQASM 2.0;"
+                               "include \"qelib1.inc\";"
+                               "qreg q[3];"
+                               "ccz q[0],q[1],q[2];\n";
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]: Why does this test use an OpenQASM file, while all others directly use the `QuantumComputation` API? I think I'd prefer to also have this test written as
`qc.mcz(...)`

File: test/zx/test_zx_functionality.cpp [hunk 11]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+  EXPECT_TRUE(d.connected(d.getInput(2), d.getOutput(2)));
+}
+
+TEST_F(ZXFunctionalityTest, MultiControlX) {
   using namespace qc::literals;
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]:
```suggestion
```
This isn't used here as far as I can tell.

File: test/zx/test_zx_functionality.cpp [hunk 12]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
   EXPECT_TRUE(diag.isIdentity());
 }
 
-TEST_F(ZXFunctionalityTest, UnsupportedMultiControl) {
+TEST_F(ZXFunctionalityTest, CRZ) {
+  using namespace qc::literals;
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]:
```suggestion
```
This isn't used here as far as I can tell.

File: test/zx/test_zx_functionality.cpp [hunk 13]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+
+  EXPECT_TRUE(FunctionalityConstruction::transformableToZX(&qc));
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+}
+
+TEST_F(ZXFunctionalityTest, MultiCZ) {
+  using namespace qc::literals;
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]:
```suggestion
```
This isn't used here as far as I can tell.

File: test/zx/test_zx_functionality.cpp [hunk 14]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+
+  d.concat(dPrime.invert());
+
+  fullReduce(d);
+
+  EXPECT_TRUE(FunctionalityConstruction::transformableToZX(&qc));
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]: Given how often this sequence of calls is repeated throughout the tests here, I think it would be worth to extract this into a separate function in this file to reduce the amount of duplication.

File: test/zx/test_zx_functionality.cpp (hunk 6 above)
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]: This is the same test as the `ccz` test and can be deduplicated

File: test/zx/test_zx_functionality.cpp [hunk 15]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+  EXPECT_TRUE(d.connected(d.getInput(2), d.getOutput(2)));
+  EXPECT_TRUE(d.connected(d.getInput(3), d.getOutput(3)));
+}
+
+TEST_F(ZXFunctionalityTest, MultiControlRZ) {
+  using namespace qc::literals;
+  qc = qc::QuantumComputation(3);
+  qc.mcrz(PI / 4, {1, 2}, 0);
+  qc.mcrz(-PI / 4, {1, 2}, 0);
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]: This test is not following the structure of the other tests.
The pattern for the mcrz gate decomposition should be the same as above (but with more controls)
```
qcPrime.cx(0, 1);
qcPrime.rz(-PI / 4, 1);
qcPrime.cx(0, 1);
qcPrime.rz(PI / 4, 1);
```

File: test/zx/test_zx_functionality.cpp [hunk 16]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+  EXPECT_TRUE(d.connected(d.getInput(2), d.getOutput(2)));
+  EXPECT_TRUE(d.connected(d.getInput(3), d.getOutput(3)));
+}
+
+TEST_F(ZXFunctionalityTest, MultiControlXLarger) {
+  using namespace qc::literals;
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]:
```suggestion
```
This isn't used here as far as I can tell.

File: test/zx/test_zx_functionality.cpp [hunk 17]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+  EXPECT_TRUE(d.connected(d.getInput(2), d.getOutput(2)));
+  EXPECT_TRUE(d.connected(d.getInput(3), d.getOutput(3)));
+  EXPECT_TRUE(d.connected(d.getInput(4), d.getOutput(4)));
+}
+
+TEST_F(ZXFunctionalityTest, MultiControlX0) {
+  using namespace qc::literals;
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]:
```suggestion
```
This isn't used here as far as I can tell.

File: test/zx/test_zx_functionality.cpp [hunk 18]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+
+  fullReduce(d);
+
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+}
+
+TEST_F(ZXFunctionalityTest, MultiControlX1) {
+  using namespace qc::literals;
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]:
```suggestion
```
This isn't used here as far as I can tell.

File: test/zx/test_zx_functionality.cpp [hunk 19]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+  fullReduce(d);
+
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+}
+
+TEST_F(ZXFunctionalityTest, MultiControlZ) {
+  using namespace qc::literals;
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]:
```suggestion
```
This isn't used here as far as I can tell.

File: test/zx/test_zx_functionality.cpp [hunk 20]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+  EXPECT_TRUE(d.connected(d.getInput(2), d.getOutput(2)));
+  EXPECT_TRUE(d.connected(d.getInput(3), d.getOutput(3)));
+}
+
+TEST_F(ZXFunctionalityTest, MultiControlZ0) {
+  using namespace qc::literals;
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]:
```suggestion
```
This isn't used here as far as I can tell.

File: test/zx/test_zx_functionality.cpp [hunk 21]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+
+  fullReduce(d);
+
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+}
+
+TEST_F(ZXFunctionalityTest, MultiControlZ1) {
+  using namespace qc::literals;
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]:
```suggestion
```
This isn't used here as far as I can tell.

File: test/zx/test_zx_functionality.cpp [hunk 22]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+  fullReduce(d);
+
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+}
+
+TEST_F(ZXFunctionalityTest, MultiControlZ2) {
+  using namespace qc::literals;
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]:
```suggestion
```
This isn't used here as far as I can tell.

File: test/zx/test_zx_functionality.cpp [hunk 23]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+  EXPECT_TRUE(d.connected(d.getInput(2), d.getOutput(2)));
+  EXPECT_TRUE(d.connected(d.getInput(3), d.getOutput(3)));
+}
+
+TEST_F(ZXFunctionalityTest, MultiControlRZ) {
+  using namespace qc::literals;
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]:
```suggestion
```
This isn't used here as far as I can tell.

File: test/zx/test_zx_functionality.cpp [hunk 24]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+  EXPECT_TRUE(d.connected(d.getInput(1), d.getOutput(1)));
+  EXPECT_TRUE(d.connected(d.getInput(2), d.getOutput(2)));
+}
+
+TEST_F(ZXFunctionalityTest, MultiControlRZ0) {
+  using namespace qc::literals;
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]:
```suggestion
```
This isn't used here as far as I can tell.

File: test/zx/test_zx_functionality.cpp [hunk 25]
```diff
@@ -219,14 +219,336 @@ TEST_F(ZXFunctionalityTest, Compound) {
...
+
+  fullReduce(d);
+
+  EXPECT_TRUE(d.isIdentity());
+  EXPECT_TRUE(d.globalPhaseIsZero());
+  EXPECT_TRUE(d.connected(d.getInput(0), d.getOutput(0)));
+}
+
+TEST_F(ZXFunctionalityTest, MultiControlRZ1) {
+  using namespace qc::literals;
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp]:
```suggestion
```
This isn't used here as far as I can tell.

File: src/zx/FunctionalityConstruction.cpp [hunk 26]
```diff
@@ -307,6 +307,127 @@ void FunctionalityConstruction::addCcx(ZXDiagram& diag, const Qubit ctrl0,
...
+
+void FunctionalityConstruction::addCrz(ZXDiagram& diag,
+                                       const PiExpression& phase,
+                                       const Qubit q0, const Qubit q1,
+                                       std::vector<Vertex>& qubits) {
+  // CRZ decomposition uses reversed CNOT direction
+  addCnot(diag, q1, q0, qubits);
+  addZSpider(diag, q0, qubits, -phase / 2);
+  addZSpider(diag, q1, qubits, phase / 2);
```
Comment (burgholzer) [inline src/zx/FunctionalityConstruction.cpp]:
```suggestion
  addZSpider(diag, q1, qubits, phase / 2);
  addCnot(diag, q1, q0, qubits);
  addZSpider(diag, q0, qubits, -phase / 2);
```
These commute, so it does not really matter too much, but for consistency with the `mcrz` patter, I'd prefer this order.

File: src/zx/FunctionalityConstruction.cpp [hunk 27]
```diff
@@ -307,6 +307,127 @@ void FunctionalityConstruction::addCcx(ZXDiagram& diag, const Qubit ctrl0,
...
+      for (std::size_t q = 0; q < qubits.size(); ++q) {
+        const auto qb = static_cast<Qubit>(q);
+        if (std::ranges::find(controls, qb) == controls.end()) {
+          anc = qb;
+          break;
+        }
+      }
+      if (!anc.has_value()) {
+        throw ZXException("No ancilla qubit available for MCX decomposition");
+      }
```
Comment (burgholzer) [inline src/zx/FunctionalityConstruction.cpp]: This is unreachable code, right? There are more than `nctrl+1` qubits available, so there has to be one that is not in the list of controls+target. So `anc` does not need to be an optional.

I also think that you could be using https://en.cppreference.com/w/cpp/algorithm/set_difference.html here.

File: src/zx/FunctionalityConstruction.cpp [hunk 28]
```diff
@@ -307,6 +307,127 @@ void FunctionalityConstruction::addCcx(ZXDiagram& diag, const Qubit ctrl0,
...
+                                       std::vector<Qubit> controls,
+                                       const Qubit target,
+                                       std::vector<Vertex>& qubits) {
+  const Qubit nextControl = controls.back();
+  controls.pop_back();
+
+  addCrz(diag, PiExpression(PiRational(1, 2)), nextControl, target, qubits);
+  addMcx(diag, controls, target, qubits);
+  addCrz(diag, PiExpression(-PiRational(1, 2)), nextControl, target, qubits);
+  addMcx(diag, controls, target, qubits);
```
Comment (burgholzer) [inline src/zx/FunctionalityConstruction.cpp]: Wouldn't it be easier to either:
- have `mcz` implement the logic as `H -- mcx -- H`, or
- have `mcx` be implemented as `H -- mcz -- H`

Does one of these yield a shorter decomposition?

File: src/zx/FunctionalityConstruction.cpp [hunk 29]
```diff
@@ -578,15 +702,39 @@ FunctionalityConstruction::parseOp(ZXDiagram& diag, op_it it, op_it end,
         ctrl1 = static_cast<Qubit>(p.at(ctrl.qubit));
       }
     }
+    std::vector<Qubit> controls;
+    for (const auto& ctrl : op->getControls()) {
+      controls.push_back(static_cast<Qubit>(p.at(ctrl.qubit)));
+    }
```
Comment (burgholzer) [inline src/zx/FunctionalityConstruction.cpp]: This can just be inlined as `{ctrl0, ctrl1}` in the `addMcrz` call below.

File: src/zx/FunctionalityConstruction.cpp [hunk 30]
```diff
@@ -578,15 +702,39 @@ FunctionalityConstruction::parseOp(ZXDiagram& diag, op_it it, op_it end,
...
+    default:
+      throw ZXException("Unsupported Multi-control operation: " +
+                        qc::toString(op->getType()));
+    }
+  } else if (op->getNtargets() == 1) {
+    const auto target = static_cast<Qubit>(p.at(op->getTargets().front()));
+    std::vector<Qubit> controls;
+    for (const auto& ctrl : op->getControls()) {
+      controls.push_back(static_cast<Qubit>(p.at(ctrl.qubit)));
+    }
```
Comment (burgholzer) [inline src/zx/FunctionalityConstruction.cpp:796]: Always good to use `reserve` to preallocate the right size for the container. And to use `emplace_back` over `push_back`.

**Review by burgholzer — CHANGES_REQUESTED** [review]
Many thanks @keefehuang for this contribution! This is great to see. 🙌🏼 
I looked through all the code and you can find some comments inline.
As for the suggestions, you should be able to directly go to the "Files Changed" tab on GitHub and go through the comments, add the suggestions to a batch and commit them in one go.

Besides the inline comments, I was wondering whether we could fairly easily extend the supported gates here by using well known gate decompositions of these gates. Gates that come to mind are `SWAP`, `RXX`, `RZZ`, `RYY`, `RZX`, `DCX`, `MCRX`, `MCP`.
None of these should add too much complexity here. What do you think?

**Comment by burgholzer** [comment]
@keefehuang Just wanted to check in here. What's the current status for this PR?

File: test/zx/test_zx_functionality.cpp (hunk 10 above)
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp]: Updated

File: test/zx/test_zx_functionality.cpp (hunk 11 above)
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp]: Removed

File: test/zx/test_zx_functionality.cpp (hunk 13 above)
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp]: Similarly removed in all cases

File: test/zx/test_zx_functionality.cpp (hunk 14 above)
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp]: Refactored

File: src/zx/FunctionalityConstruction.cpp (hunk 26 above)
Comment (keefehuang) [reply src/zx/FunctionalityConstruction.cpp]: These don't actually commute. However, this is an implementation that allows for more gate parallelism. (You can check that moving this around breaks the equality).

File: src/zx/FunctionalityConstruction.cpp (hunk 27 above)
Comment (keefehuang) [reply src/zx/FunctionalityConstruction.cpp]: Removed unreachable code.
Implemented set_difference.

File: src/zx/FunctionalityConstruction.cpp (hunk 28 above)
Comment (keefehuang) [reply src/zx/FunctionalityConstruction.cpp]: This is effectively a MCx based implementation. The MCz helps reduce the MCz initial cost by a few gates compared to the H-MCX-H implementation.

File: src/zx/FunctionalityConstruction.cpp (hunk 29 above)
Comment (keefehuang) [reply src/zx/FunctionalityConstruction.cpp]: Inlined

File: src/zx/FunctionalityConstruction.cpp (hunk 30 above)
Comment (keefehuang) [reply src/zx/FunctionalityConstruction.cpp:796]: Should be refactored through the file.

File: src/zx/FunctionalityConstruction.cpp (hunk 26 above)
Comment (burgholzer) [reply src/zx/FunctionalityConstruction.cpp]: I am slightly confused here. By the rules of the ZX-calculus, one of these Z-spiders has to commute with the ZX, doesn't it?
This is also a standard circuit rewrite rule (commuting diagonal operators through control qubits).

File: src/zx/FunctionalityConstruction.cpp [hunk 31]
```diff
@@ -307,6 +363,125 @@ void FunctionalityConstruction::addCcx(ZXDiagram& diag, const Qubit ctrl0,
...
+
+void FunctionalityConstruction::addMcrx(ZXDiagram& diag,
+                                        const PiExpression& phase,
+                                        std::vector<Qubit> controls,
+                                        const Qubit target,
+                                        std::vector<Vertex>& qubits) {
+  addZSpider(diag, target, qubits, PiExpression(), EdgeType::Hadamard);
+  addMcrz(diag, phase, controls, target, qubits);
+  addZSpider(diag, target, qubits, PiExpression(), EdgeType::Hadamard);
+}
```
[the remark this answers is not in the document]
Comment (denialhaag) [reply src/zx/FunctionalityConstruction.cpp:404]: This is fixed, right?

File: src/zx/FunctionalityConstruction.cpp [hunk 32]
```diff
@@ -307,6 +363,125 @@ void FunctionalityConstruction::addCcx(ZXDiagram& diag, const Qubit ctrl0,
...
+    addRx(diag, PiExpression(-PiRational(1, 4)), target, qubits);
+    addZSpider(diag, target, qubits, PiExpression(), EdgeType::Hadamard);
+    addMcx(diag, second, target, qubits);
+    addZSpider(diag, target, qubits, PiExpression(), EdgeType::Hadamard);
+    const Qubit lastControl = controls.back();
+    controls.pop_back();
+    addMcphase(diag, PiExpression(PiRational(1, 2)), controls, lastControl,
+               qubits);
+  }
+}
```
[the remark this answers is not in the document]
Comment (denialhaag) [reply src/zx/FunctionalityConstruction.cpp:471]: This is fixed, right?

File: src/zx/FunctionalityConstruction.cpp [hunk 33]
```diff
@@ -307,6 +363,125 @@ void FunctionalityConstruction::addCcx(ZXDiagram& diag, const Qubit ctrl0,
...
+
+void FunctionalityConstruction::addMcz(ZXDiagram& diag,
+                                       std::vector<Qubit> controls,
+                                       const Qubit target,
+                                       std::vector<Vertex>& qubits) {
+  addZSpider(diag, target, qubits, PiExpression(), EdgeType::Hadamard);
+  addMcx(diag, controls, target, qubits);
+  addZSpider(diag, target, qubits, PiExpression(), EdgeType::Hadamard);
+}
```
[the remark this answers is not in the document]
Comment (denialhaag) [reply src/zx/FunctionalityConstruction.cpp:480]: This is fixed, right?

File: src/zx/FunctionalityConstruction.cpp [hunk 34]
```diff
@@ -582,20 +768,119 @@ FunctionalityConstruction::parseOp(ZXDiagram& diag, op_it it, op_it end,
...
+        addMcrzz(diag, phase, controls, target, target2, qubits);
+      }
+      addZSpider(diag, target2, qubits, PiExpression(), EdgeType::Hadamard);
+      break;
+    }
+    default:
+      throw ZXException("Unsupported Multi-control operation (" +
+                        std::to_string(op->getNcontrols()) + " ctrls)" +
+                        qc::toString(op->getType()));
+    }
```
[the remark this answers is not in the document]
Comment (denialhaag) [reply src/zx/FunctionalityConstruction.cpp]: This is fixed, right?

File: test/zx/test_zx_functionality.cpp [hunk 35]
```diff
@@ -35,6 +35,25 @@ class ZXFunctionalityTest : public ::testing::Test {
...
+  auto d2 = FunctionalityConstruction::buildFunctionality(&qc2);
+  d1.concat(d2.invert());
+  fullReduce(d1);
+  EXPECT_TRUE(d1.isIdentity());
+  EXPECT_TRUE(d1.globalPhaseIsZero());
+  for (const auto q : qubits) {
+    ASSERT_LT(q, qc1.getNqubits());
+    EXPECT_TRUE(d1.connected(d1.getInput(q), d1.getOutput(q)));
+  }
+}
```
[the remark this answers is not in the document]
Comment (denialhaag) [reply test/zx/test_zx_functionality.cpp]: This is fixed, right?

File: include/mqt-core/zx/FunctionalityConstruction.hpp [hunk 36]
```diff
@@ -85,8 +85,14 @@ class FunctionalityConstruction {
...
   static void addCphase(ZXDiagram& diag, const PiExpression& phase, Qubit ctrl,
                         Qubit target, std::vector<Vertex>& qubits);
+  static void addMcphase(ZXDiagram& diag, const PiExpression& phase,
+                         const std::vector<Qubit>& controls, Qubit target,
+                         std::vector<Vertex>& qubits);
   static void addSwap(ZXDiagram& diag, Qubit target, Qubit target2,
                       std::vector<Vertex>& qubits);
+  static void addMcswap(ZXDiagram& diag, const std::vector<Qubit>& controls,
+                        Qubit target, Qubit target2,
+                        std::vector<Vertex>& qubits);
```
[the remark this answers is not in the document]
Comment (denialhaag) [reply include/mqt-core/zx/FunctionalityConstruction.hpp:95]: Those are static functions that are not user-facing. Like the helper functions that were already present in this file, they do not need docstrings.

**Comment by denialhaag** [comment]
@burgholzer, this should be ready now. I only cleaned up some minor things and applied your open suggestion (https://github.com/munich-quantum-toolkit/core/pull/1380#discussion_r2675414146). The diff was a bit hard to understand, and I had initially also thought the statements didn't commute, but you were right. The open CoreRabbit comments had already been addressed by @keefehuang, but CodeRabbit had not resolved them.

File: src/zx/FunctionalityConstruction.cpp [hunk 37]
```diff
@@ -286,6 +326,22 @@ void FunctionalityConstruction::addSwap(ZXDiagram& diag, const Qubit target,
...
+                                          std::vector<Vertex>& qubits) {
+  std::vector controls1 = controls;
+  std::vector controls2 = controls;
+
+  controls1.emplace_back(target);
+  controls2.emplace_back(target2);
+
+  addMcx(diag, controls1, target2, qubits);
+  addMcx(diag, controls2, target, qubits);
+  addMcx(diag, controls1, target2, qubits);
```
Comment (burgholzer) [inline src/zx/FunctionalityConstruction.cpp:342]: This is an inefficient decomposition as only one of the mcx gates actually needs the controls.

```suggestion
  std::vector controls = controls;
  controls.emplace_back(target2);

  addCnot(diag, target, target2, qubits);
  addMcx(diag, controls, target, qubits);
  addCnot(diag, target, target2, qubits);
```

File: src/zx/FunctionalityConstruction.cpp [hunk 38]
```diff
@@ -429,21 +601,27 @@ FunctionalityConstruction::parseOp(ZXDiagram& diag, op_it it, op_it end,
...
       const auto target2 = static_cast<Qubit>(p.at(op->getTargets()[1]));
       const auto& phase = parseParam(op.get(), 0);
+      addZSpider(diag, target2, qubits, PiExpression(), EdgeType::Hadamard);
       if (phase.isConstant()) {
         addRzx(diag, phase, target, target2, qubits, op->getParameter().at(0));
       } else {
         addRzx(diag, phase, target, target2, qubits);
       }
+      addZSpider(diag, target2, qubits, PiExpression(), EdgeType::Hadamard);
       break;
```
Comment (burgholzer) [inline src/zx/FunctionalityConstruction.cpp:625]: These changes feel strange to me. @denialhaag could you maybe check why they were not necessary before?

File: test/zx/test_zx_functionality.cpp [hunk 39]
```diff
@@ -391,16 +469,171 @@ TEST_F(ZXFunctionalityTest, XXminusYY) {
...
+
+TEST_F(ZXFunctionalityTest, CSWAP) {
+  qc = qc::QuantumComputation(3);
+  qc.mcswap({0}, 1, 2);
+
+  auto qcPrime = qc::QuantumComputation(3);
+  qcPrime.mcx({0, 1}, 2);
+  qcPrime.mcx({0, 2}, 1);
+  qcPrime.mcx({0, 1}, 2);
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp:494]:
```suggestion
  auto qcPrime = qc::QuantumComputation(3);
  qcPrime.cx(1, 2);
  qcPrime.mcx({0, 2}, 1);
  qcPrime.cx(1, 2);
```

File: test/zx/test_zx_functionality.cpp [hunk 40]
```diff
@@ -391,16 +469,171 @@ TEST_F(ZXFunctionalityTest, XXminusYY) {
...
+}
+
+TEST_F(ZXFunctionalityTest, MCSWAP) {
+  qc = qc::QuantumComputation(4);
+  qc.mcswap({0, 1}, 2, 3);
+
+  auto qcPrime = qc::QuantumComputation(4);
+  qcPrime.mcx({0, 1, 2}, 3);
+  qcPrime.mcx({0, 1, 3}, 2);
+  qcPrime.mcx({0, 1, 2}, 3);
```
Comment (burgholzer) [inline test/zx/test_zx_functionality.cpp:506]:
```suggestion
  auto qcPrime = qc::QuantumComputation(4);
  qcPrime.cx(2, 3);
  qcPrime.mcx({0, 1, 3}, 2);
  qcPrime.cx(2, 3);
```

File: src/zx/FunctionalityConstruction.cpp (hunk 38 above)
Comment (keefehuang) [reply src/zx/FunctionalityConstruction.cpp:616]: Sorry, these were added as the MC variants were based on MCRZZ. These should not be changed.

**Comment by keefehuang** [comment]
Apologies, I started a new job and this fell of the radar. I did address the code rabbit comments last time but then it fell off the radar. Hopefully, these resolve the issues.

File: src/zx/FunctionalityConstruction.cpp (hunk 37 above)
Comment (keefehuang) [reply src/zx/FunctionalityConstruction.cpp]: Updated

File: test/zx/test_zx_functionality.cpp (hunk 39 above)
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp]: Updated

File: test/zx/test_zx_functionality.cpp (hunk 40 above)
Comment (keefehuang) [reply test/zx/test_zx_functionality.cpp]: Updated

File: test/zx/test_zx_functionality.cpp [hunk 41]
```diff
@@ -391,16 +469,171 @@ TEST_F(ZXFunctionalityTest, XXminusYY) {
...
+
+TEST_F(ZXFunctionalityTest, MCT) {
+  qc = qc::QuantumComputation(4);
+  qc.mct({0, 1, 2}, 3);
+
+  auto qcPrime = qc::QuantumComputation(4);
+  qcPrime.mct({0, 1, 2}, 3);
+
+  checkEquivalence(qc, qcPrime, {0, 1, 2, 3});
+}
```
[the remark this answers is not in the document]
Comment (burgholzer) [reply test/zx/test_zx_functionality.cpp:638]: Yeah, this is fine for now. It might be updated in a future PR.

File: include/mqt-core/zx/FunctionalityConstruction.hpp [hunk 42]
```diff
@@ -113,6 +124,24 @@ class FunctionalityConstruction {
...
+  static void addCrz(ZXDiagram& diag, const PiExpression& phase,
+                     const Qubit control, const Qubit target,
+                     std::vector<Vertex>& qubits);
+  static void addMcrz(ZXDiagram& diag, const PiExpression& phase,
+                      std::vector<Qubit> controls, const Qubit target,
+                      std::vector<Vertex>& qubits);
+  static void addMcx(ZXDiagram& diag, std::vector<Qubit> controls,
+                     const Qubit target, std::vector<Vertex>& qubits);
+  static void addMcz(ZXDiagram& diag, std::vector<Qubit> controls,
+                     const Qubit target, std::vector<Vertex>& qubits);
```
[the remark this answers is not in the document]
Comment (denialhaag) [reply include/mqt-core/zx/FunctionalityConstruction.hpp]: This should be fixed now, right? I should have used `const std::vector<Qubit>&` wherever possible. I have edited all declarations using `const Qubit`.

[the remark this answers is not in the document]
Comment (denialhaag) [reply include/mqt-core/zx/FunctionalityConstruction.hpp]: The default branch in `addMcx()` calls `controls.pop_back()`.

File: src/zx/FunctionalityConstruction.cpp [hunk 43]
```diff
@@ -207,6 +233,20 @@ void FunctionalityConstruction::addRzx(
...
+    std::vector<Vertex>& qubits,
+    const std::optional<double>& unconvertedPhase) {
+  addRzz(diag, phase / 2, target, target2, qubits, unconvertedPhase);
+  addMcx(diag, controls, target, qubits);
+  addRzz(diag, -phase / 2, target, target2, qubits,
+         unconvertedPhase.has_value()
+             ? std::optional<double>(-unconvertedPhase.value())
+             : std::nullopt);
+  addMcx(diag, controls, target, qubits);
+}
```
[the remark this answers is not in the document]
Comment (denialhaag) [reply src/zx/FunctionalityConstruction.cpp:251]: @burgholzer, I admittedly don't know a lot about ZX calculus, but I have implemented the suggestion. Is @coderabbitai correct here? 🤔

File: src/zx/FunctionalityConstruction.cpp [hunk 44]
```diff
@@ -565,7 +737,7 @@ FunctionalityConstruction::parseOp(ZXDiagram& diag, op_it it, op_it end,
       throw ZXException("Unsupported Controlled Operation: " +
                         qc::toString(op->getType()));
     }
-  } else if (op->getNcontrols() == 2) {
+  } else if (op->getNcontrols() == 2 && op->getNtargets() == 1) {
     // three-qubit controlled gates (ccx or ccz)
```
[the remark this answers is not in the document]
Comment (denialhaag) [reply src/zx/FunctionalityConstruction.cpp]: This is fixed now, right?

File: src/zx/FunctionalityConstruction.cpp [hunk 45]
```diff
@@ -307,6 +364,116 @@ void FunctionalityConstruction::addCcx(ZXDiagram& diag, const Qubit ctrl0,
...
+    addRx(diag, PiExpression(-PiRational(1, 4)), target, qubits);
+    addZSpider(diag, target, qubits, PiExpression(), EdgeType::Hadamard);
+    addMcx(diag, second, target, qubits);
+    addZSpider(diag, target, qubits, PiExpression(), EdgeType::Hadamard);
+    const Qubit lastControl = controls.back();
+    controls.pop_back();
+    addMcphase(diag, PiExpression(PiRational(1, 2)), controls, lastControl,
+               qubits);
+  }
+}
```
[the remark this answers is not in the document]
Comment (denialhaag) [reply src/zx/FunctionalityConstruction.cpp:468]: @coderabbitai, you probably have a point. @burgholzer, do you think we should leave this as a potential follow-up or look into it here? 🤔

[the remark this answers is not in the document]
Comment (burgholzer) [reply src/zx/FunctionalityConstruction.cpp:468]: @denialhaag @coderabbitai The current decomposition does not feel particularly efficient, I agree on that part.
How easy would this be to fix?
The ancillary free decomposition will always break down into an exponentially sized list of elementary elements. The key simplification that would really make a difference is the use of ancillary qubits. But that is, for sure, out of the scope for this PR.
If here is a better, more efficient ancillary-free MCX decomposition that we could employ here, it is for sure worth a shot. The fewer ZX spiders, the better.

[the remark this answers is not in the document]
Comment (burgholzer) [reply src/zx/FunctionalityConstruction.cpp:468]: @coderabbitai How about you first show how the Gidney implementation would look like here in the comments?

[the remark this answers is not in the document]
Comment (burgholzer) [reply src/zx/FunctionalityConstruction.cpp:468]: @coderabbitai yeah. please open a detailed follow-up issue. leave the assignment open.

**Comment by denialhaag** [comment]
@coderabbitai review

**Comment by denialhaag** [comment]
Merging this now! Thanks a lot for the contribution, @keefehuang! 🙂
